apiVersion: v1
kind: Config
clusters:
- name: "jambonz-hetzner-prod"
  cluster:
    server: "https://rancher.vultik.com/k8s/clusters/c-m-glmlhqxk"

users:
- name: "jambonz-hetzner-prod"
  user:
    token: "kubeconfig-u-b2v8gg5l77:ttvhf6n9gzf2rxgjh8zjqq7svtbrxx4pc4fgcv9qms4lkmmr87gq84"


contexts:
- name: "jambonz-hetzner-prod"
  context:
    user: "jambonz-hetzner-prod"
    cluster: "jambonz-hetzner-prod"

current-context: "jambonz-hetzner-prod"
