apiVersion: v1
kind: Config
clusters:
- name: "jambonz-hz-5"
  cluster:
    server: "https://rancher.vultik.com/k8s/clusters/c-qwzqz"

users:
- name: "jambonz-hz-5"
  user:
    token: "kubeconfig-u-b2v8gwmrhr:5mxd8lhmh5q5drmjssxtknjbdnb7z5qbqkhhsw7f6z2l44rzf9nl5d"


contexts:
- name: "jambonz-hz-5"
  context:
    user: "jambonz-hz-5"
    cluster: "jambonz-hz-5"

current-context: "jambonz-hz-5"
