apiVersion: v1
kind: Config
clusters:
- name: "jambonz-hz-3"
  cluster:
    server: "https://rancher.vultik.com/k8s/clusters/c-ztgm9"

users:
- name: "jambonz-hz-3"
  user:
    token: "kubeconfig-u-b2v8gb5x24:rt882g2zzqkc4w7vpvms95v57z4x4kl6b6rtlr4c2dw9m8zq69mngs"


contexts:
- name: "jambonz-hz-3"
  context:
    user: "jambonz-hz-3"
    cluster: "jambonz-hz-3"

current-context: "jambonz-hz-3"
